put "*      *    ********    ********"
put "**     *    *      *    *      *"
put "* *    *    *      *    *      *"
put "*  *   *    *      *    *      *"
put "*   *  *    *      *    *      *"
put "*    * *    *      *    *      *"
put "*     **    ********    ********"
put skip,skip
put "       *"
put "      * *"
put "     *   *"
put "    *     *"
put "   *       *"
put "  ***********"
put " *           *"
put "*             *"
